server:
  port: 8080

spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/bbs
    username: root
    password: runwild

  properties:
    hibernate:
      format_sql: true

  jpa:
    show-sql: true
    hibernate:
      ddl-auto: update

  mvc:
    pathmatch:
      matching-strategy: ant_path_matcher

jwt:
  secret:
    token: surfing